# -*- coding: utf-8 -*-
"""K-MEANS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axwzIvYOECrZ4R1e3tpnfwr-my83JQpb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/musteriler.csv')

X = veriler.iloc[:, 2:5]
Y = veriler.iloc[:, [2]]
# NUMPY ARRAY DIZI DONUSUMU
x = X.values

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3, init = 'k-means++')
kmeans.fit(X)

kmeans.cluster_centers_

sonuclar = []
for i in range(1, 10):
  kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 245)
  kmeans.fit(X)
  sonuclar.append(kmeans.inertia_)

sonuclar

plt.plot(range(len(sonuclar)), sonuclar)
plt.show()

