# -*- coding: utf-8 -*-
"""hierarchicalClustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jNK5WIh8R-G-oSQypJxrmSurnxdcvFbq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/musteriler.csv')

X = veriler.iloc[:, 2:5]
Y = veriler.iloc[:, 1:2]
# NUMPY ARRAY DIZI DONUSUMU
x = X.values

from sklearn.cluster import AgglomerativeClustering

ac = AgglomerativeClustering(n_clusters = 4, affinity = 'euclidean', linkage = 'ward')
y_pred = ac.fit_predict(x)
print(y_pred)

plt.scatter(x[y_pred == 0, 1], x[y_pred == 0, 2], s = 100, c = 'r')
plt.scatter(x[y_pred == 1, 1], x[y_pred == 1, 2], s = 100, c = 'b')
plt.scatter(x[y_pred == 2, 1], x[y_pred == 2, 2], s = 100, c = 'g')
plt.scatter(x[y_pred == 3, 1], x[y_pred == 3, 2], s = 100, c = 'y')
plt.show()

import scipy.cluster.hierarchy as sch

dendrogram = sch.dendrogram(sch.linkage(X, method = 'ward'))

